apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fizzbuzz
spec:
  replicas: 1
  template:
    metadata:
      name: fizzbuzz
      labels:
        task: api
        app: fizzbuzz
    spec:
      containers:
      - name: fizzbuzz
        image: fizzbuzz-api
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/name: fizzbuzz
    name: fizzbuzz
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  type: NodePort
  selector:
    app: fizzbuzz
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-fizzbuzz
  namespace: default
  annotations:
    nginx.org/rewrites: "serviceName=fizzbuzz rewrite=/"
    kubernetes.io/ingress.class: "nginx"
spec:
 rules:
  - host: fizzbuzz.kevinplatel.tech
    http:
      paths:
      - path: /
        backend:
          serviceName: fizzbuzz
          servicePort: 8080 # Service port